//
// Copyright (C) 2018 Aleksandar Zlateski <zlateski@mit.edu>
// Copyright (C) 2018 Zhen Jia <zhenj@princeton.edu>
// ---------------------------------------------------------------
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
#pragma once
template <>
struct r2cb_traits<3, 0>
{
    static constexpr long_t flops           = 7;
    static constexpr long_t operations      = 4;
    static constexpr long_t memory_accesses = 6;
    static constexpr long_t stack_vars      = 6;
    static constexpr long_t constants       = 2;
};
/* Generated by: ./gen_r2cb.native -fma -reorder-insns -schedule-for-pipeline
 * -compact -variables 30 -pipeline-latency 12 -sign 1 -n 3 -skip-k 0 -name r2cb
 * -standalone */

/*
 * This function contains 4 FP additions, 3 FP multiplications,
 * (or, 1 additions, 0 multiplications, 3 fused multiply/add),
 * 6 stack variables, 2 constants, and 6 memory accesses
 */
template <long_t TransformSize, long_t SkippedOutputs, long_t rs, long_t cs>
inline __attribute__((always_inline))
typename std::enable_if<TransformSize == 3 && SkippedOutputs == 0>::type
r2cb(SIMD_FLOAT* __restrict R0, SIMD_FLOAT const* __restrict Cr,
     SIMD_FLOAT const* __restrict Ci)
{
    DK(KP1_732050807, +1.732050807568877293527446341505872366942805254);
    DK(KP2_000000000, +2.000000000000000000000000000000000000000000000);
    {
        SIMD_FLOAT T4, T1, T2, T3;
        T4            = Ci[WS(cs, 1)];
        T1            = Cr[0];
        T2            = Cr[WS(cs, 1)];
        R0[0]         = SIMD_FMADD(KP2_000000000, T2, T1);
        T3            = T1 - T2;
        R0[WS(rs, 1)] = SIMD_FNMADD(KP1_732050807, T4, T3);
        R0[WS(rs, 2)] = SIMD_FMADD(KP1_732050807, T4, T3);
    }
}

template <>
struct r2cb_traits<3, 1>
{
    static constexpr long_t flops           = 5;
    static constexpr long_t operations      = 3;
    static constexpr long_t memory_accesses = 5;
    static constexpr long_t stack_vars      = 5;
    static constexpr long_t constants       = 1;
};
/* Generated by: ./gen_r2cb.native -fma -reorder-insns -schedule-for-pipeline
 * -compact -variables 30 -pipeline-latency 12 -sign 1 -n 3 -skip-k 1 -name r2cb
 * -standalone */

/*
 * This function contains 3 FP additions, 2 FP multiplications,
 * (or, 1 additions, 0 multiplications, 2 fused multiply/add),
 * 5 stack variables, 1 constants, and 5 memory accesses
 */
template <long_t TransformSize, long_t SkippedOutputs, long_t rs, long_t cs>
inline __attribute__((always_inline))
typename std::enable_if<TransformSize == 3 && SkippedOutputs == 1>::type
r2cb(SIMD_FLOAT* __restrict R0, SIMD_FLOAT const* __restrict Cr,
     SIMD_FLOAT const* __restrict Ci)
{
    DK(KP1_732050807, +1.732050807568877293527446341505872366942805254);
    {
        SIMD_FLOAT T4, T1, T2, T3;
        T4            = Ci[WS(cs, 1)];
        T1            = Cr[0];
        T2            = Cr[WS(cs, 1)];
        T3            = T1 - T2;
        R0[WS(rs, 1)] = SIMD_FMADD(KP1_732050807, T4, T3);
        R0[0]         = SIMD_FNMADD(KP1_732050807, T4, T3);
    }
}

template <>
struct r2cb_traits<3, 2>
{
    static constexpr long_t flops           = 3;
    static constexpr long_t operations      = 2;
    static constexpr long_t memory_accesses = 4;
    static constexpr long_t stack_vars      = 4;
    static constexpr long_t constants       = 1;
};
/* Generated by: ./gen_r2cb.native -fma -reorder-insns -schedule-for-pipeline
 * -compact -variables 30 -pipeline-latency 12 -sign 1 -n 3 -skip-k 2 -name r2cb
 * -standalone */

/*
 * This function contains 2 FP additions, 1 FP multiplications,
 * (or, 1 additions, 0 multiplications, 1 fused multiply/add),
 * 4 stack variables, 1 constants, and 4 memory accesses
 */
template <long_t TransformSize, long_t SkippedOutputs, long_t rs, long_t cs>
inline __attribute__((always_inline))
typename std::enable_if<TransformSize == 3 && SkippedOutputs == 2>::type
r2cb(SIMD_FLOAT* __restrict R0, SIMD_FLOAT const* __restrict Cr,
     SIMD_FLOAT const* __restrict Ci)
{
    DK(KP1_732050807, +1.732050807568877293527446341505872366942805254);
    {
        SIMD_FLOAT T1, T3, T2;
        T1    = Cr[0];
        T3    = Cr[WS(cs, 1)];
        T2    = Ci[WS(cs, 1)];
        R0[0] = SIMD_FMADD(KP1_732050807, T2, T1) - T3;
    }
}
